// GENERATED by scripts/build-manifest.mjs — do not edit by hand. Slug → asset HTML (Text modules).
import a0 from "../assets/testasset0000000000000/index.html";
export const assetModules: Record<string, string> = {
  "testasset0000000000000": a0,
};
