// GENERATED by scripts/build-manifest.mjs — do not edit by hand. Confidential (slug→title = client
// identities, spec §7); compiled into the Worker, NEVER routable.
export const manifest: Record<string, { title: string }> = {};
