// GENERATED by scripts/build-manifest.mjs — do not edit by hand (fixture entry hand-seeded in
// Task 3.2; Task 6.2's build regenerates this file identically from assets/ + the registry).
import a0 from "../assets/testasset0000000000000/index.html";
export const assetModules: Record<string, string> = {
  testasset0000000000000: a0,
};
