// GENERATED by scripts/build-manifest.mjs — do not edit by hand (fixture entry hand-seeded in
// Task 3.2; Task 6.2's build regenerates this file identically from assets/ + the registry).
export const manifest: Record<string, { title: string }> = {
  testasset0000000000000: { title: "Test Fixture" },
};
